version: '3'

services:
  database:
   image: postgres:14
   container_name: postgres
   ports:
     - 5432:5432
   volumes:
     - db-store:/var/lib/postgresql/data
   environment:
    - POSTGRES_PASSWORD=password
volumes:
  db-store: